spring.application.name=personalFinanceManager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_finance_manager
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#! This defines what should happen with db when app start & shutdowns
spring.jpa.hibernate.ddl-auto=update

